### ISSUE TITLE
Adding Generic CPR to Token HUD

### ISSUE THREAD

**Issue by stgreenb** [MotoMoto1234/Midi-Wiki#1]
Appreciate the write up on adding CPR generic actions to token HUD, but are [the instructions](https://github.com/MotoMoto1234/Midi-Wiki/wiki/Tutorials-%E2%80%90-How-to-Make-CPR-Actions-in-Token-Action-Hud) still valid? 

Everything tracks fine, but the last step, step 10, the UI is a little different (and doesn't seem to work).
I do have a new menu item of "generic" 
![image](https://github.com/MotoMoto1234/Midi-Wiki/assets/18483964/c83d79d1-55dc-4d80-93d9-69c35d75ae2a)

But when I edit it and add the "Group: Generic Actions" (not seeing a sub-category which is what the instructions imply),  
![image](https://github.com/MotoMoto1234/Midi-Wiki/assets/18483964/4a9b45ca-cc2e-4551-b25a-f5de76ead71e)

the generic actions are all empty. 
![image](https://github.com/MotoMoto1234/Midi-Wiki/assets/18483964/9d6dcd52-a720-493b-ba12-abf285e208b1)

Note I am using Token Action HUD D&D 5e v1.5.1

**Comment by MotoMoto1234** [comment]
I believe that is a player viewing it.  The player needs permissions to the macro compendium.

**Comment by MotoMoto1234** [comment]
Added an entry to remind users to make sure players have access to the compendium.
