### ISSUE TITLE
Add silvery barbs and check that books spell list against the list

### ISSUE THREAD

**Issue by MotoMoto1234** [MotoMoto1234/Midi-Wiki#4]
I missed silvery barbs, and I should confirm the book its from and make sure its entire contents weren't left out also.

**Comment by Skyl3lazer** [comment]
Barbs is from the Strixhaven MTG tie-in. https://dnd.wizards.com/products/strixhaven-curriculum-chaos

There's only 5 spells in it, and you have the other four. You have the one ancestry (Owlin), the two feats (Strixhaven Initiate and Mascot), and all of the items from it.

There was a UA that had some other stuff for the setting https://media.wizards.com/2021/dnd/downloads/UA2021_06_08_MagesStrixhaven.pdf including subclasses that were shared between Wizards/Bards/Warlocks but they didn't make it into the final book.

**Comment by MotoMoto1234** [comment]
I actually resolved this 2 weeks ago and forgot to close the issue heh.  I believe everything is in, only 3-4 spells were missing.  I owned the content but had it excluded in my campaign so I hadn't seen stuff missing when I used a script to make a list out of my compendiums.
